### ISSUE TITLE
Implement query: get run by <<something>>

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/wes-argo-api#8]
- create an query to the Workflow ES that talks to the index
- the WES fields to query from this index are `analysis_id`, `run_id`, `state`, `work_dir`

## Exit Criteria 
- [ ] Can query the graphQL endpoint against any of these variables and see which RUNS meet this criteria

**Comment by rosibaj** [comment]
Issue moved to [icgc-argo/workflow-search #31](https://github.com/icgc-argo/workflow-search/issues/31) via [**ZenHub**](https://www.zenhub.com/)
